volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  proxy:
    driver: bridge

services:
  nginx:
    image: docker.io/laimick/monitoring
    container_name: nginx
    depends_on:
      - grafana
      - prometheus
      - node-exporter
    ports:
      - 80:80
    networks:
      - proxy
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - proxy
    expose:
      - 3000
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    networks:
      - proxy
    ports:
      - 9090:9090
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - proxy
    ports:
      - 9100:9100
    restart: unless-stopped
